filter:
    excluded_paths:
        - var/*
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - 'vendor/*'
        - 'web/bootstrap/*'
        - 'web/chartjs/*'
        - 'web/static/js/vendor/*'
        - '*.min.js'
build:
    project_setup:
        before:
            - composer self-update
    tests:
        override:
            -
                command: composer test
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
